inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-erb

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/*.ru"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
    - "**/*.erb" # analiza ERB
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "tmp/**/*"
